### PR TITLE
Support OAuth 2 Refresh Tokens

### PR DESCRIPTION
**Pull request by pdtyreus**
This is a continuation of Pull Request #600 to support OAuth 2 and OAuth 1 specific functionality, especially the ability to refresh an OAuth 2 token.

The main difference is that this branch contains the work rebased against the changes in master for clarity.

See also #596

### CODE REVIEW

**Comment by kullfar** [comment]
Yeah! Cool. Thanks for the work you've done.
I have looked a bit already, will look closer today/tomorrow

**Comment by kullfar** [comment]
I have partly reviewed your PR.
I created https://github.com/scribejava/scribejava/tree/refresh_tokens branch with your PR and added some commits with my fixes/changes.
But I didn't complete yet. Will add some more commits after full "scan" of your changes ;-)

**Comment by kullfar** [comment]
Fuh... It's ready and in the master.
I've changed a lot, but seems like the most interesting part of code is in master now.
You can try and check it

**Comment by pdtyreus** [comment]
Thanks I will try it out.

**Pull request closed without merging**
