### PR TITLE
Added Automatic OAuth2 API

### PR DESCRIPTION
**Pull request by ramsrib**

### CODE REVIEW

**Comment by kullfar** [comment]
Hi,
Thanks for the Pull Request.
I need test app credentials and test user credentials to run the example.

**Comment by ramsrib** [comment]
@kullfar Will you be able to create a test app in https://developer.automatic.com/my-apps to get the credentials?

**Comment by kullfar** [comment]
Sorry, I can't register the account and/or app. It's time consuming task for me (c) https://github.com/scribejava/scribejava/wiki/FAQ#when-will-you-support-insert_api_here-

**Comment by ramsrib** [comment]
Sent you the OAuth2 credentials thru mail. Please check and test it.

**Comment by kullfar** [comment]
Awesome, thanks!
I ran the example successfully and merged to the master.
but I have removed a couple of overrided method in API. Automatic API used the defaults (OAuth standards), no need to override.

**Pull request merged**
