### PR TITLE
Made BaseStringExtractorImpl extensible

### PR DESCRIPTION
**Pull request by mnovy**
Made the default BaseStringExtractor implementation extensible by changing method access of all private methods to protected and by moving HTTP verb and URL extraction to separate auxiliary methods.

Subclasses can now reuse existing code and alter only the methods that are desired to be altered.

### CODE REVIEW

**Comment by mnovy** [comment]
Is there any chance of this getting merged?

**Comment by kullfar** [comment]
Hi! Doesn't see anything against doing that.
The only thing I'll ask you to do - rebase on the new version of scribejava (2.0.1) please.
Class, you are changing, have moved to the new maven submodule and new java package.

**Comment by mnovy** [comment]
Thank you for the quick response! Should be ready to go now.

**Comment by kullfar** [comment]
great! thanks, have merged to the master

**Pull request merged**
