### PR TITLE
Added Instagram as a service.

### PR DESCRIPTION
**Pull request by serpensalbus**
Added and tested Instagram OAuth 2.x as Api plus example. You can manage your clients here: https://www.instagram.com/developer.

### CODE REVIEW

**Comment by kullfar** [comment]
Hi, Looks good. Thx for the job.
The last step - I need user and test application credentials to run this example

"I do not have any opportunity to register myself in ALL API providers and to register a test application." (c) https://github.com/scribejava/scribejava/wiki/FAQ#when-will-you-support-insert_api_here-

**Comment by kullfar** [comment]
outdated

**Comment by sregg** [comment]
@kullfar why outdated?
Can I use this myself?

**Comment by kullfar** [comment]
"user and test application credentials to run this example" were not provided. So I couldn't merge it to the master.
If you can update this Pull Request and provide credentials... it will be cool ;-)

**Comment by kullfar** [comment]
anyway, sure, you can use it yourself

**Pull request closed without merging**
