### PR TITLE
add netbase api

### PR DESCRIPTION
**Pull request by gjesse**

### CODE REVIEW

**Comment by kullfar** [comment]
Hi, looks ok.
I need test user and app credentials to run the example before merging to the master.
https://github.com/scribejava/scribejava/wiki/FAQ#when-will-you-support-insert_api_here-

**Comment by gjesse** [comment]
I don't think i can provide those.. i don't work for netbase and added this as part of an integration i'm working on with them. I did run the test with our account credentials but I think we'd have to get netbase to provide some for you in order to run the test yourself.

**Comment by kullfar** [comment]
Why do you think that netbase should provide them?
I don't see any problem if you register new test application and test user and send their credentials to me to run the example.

**Comment by gjesse** [comment]
I don't have a way of registering another test user with netbase.

**Comment by kullfar** [comment]
Pity, I have to close this Pull Request

**Comment by gjesse** [comment]
well that's a bummer since i've tested it & it works, but it's no big deal.

**Pull request closed without merging**
