### PR TITLE
Upgrade to Facebook API Version 2.5.

### PR DESCRIPTION
**Pull request by MichalFoksa**

### CODE REVIEW

**Comment by kullfar** [comment]
Have just merged. but with some fixes https://github.com/scribejava/scribejava/commit/7fed77379907079f61ff4f089556210b1d60be87
1.changelog entry
2.versions in examples

**Comment by kullfar** [comment]
ps.Thanks! ;-)

**Comment by MichalFoksa** [comment]
You are welcome! 
I have just created 2 additional PRs without changelog entries before I noticed your comments. Hmmm I am sorry.

**Comment by kullfar** [comment]
it's not too late to do that now ;-)

**Comment by MichalFoksa** [comment]
OK, Here you are. 
Do you have a link to good "best practice with Github" article? I am quite confused how Github creates PR, how to proceed when working on 2 independent features in parallel, etc.

**Comment by kullfar** [comment]
Sorry, I have no links. But you didn't need to close PR and open a new one. PR will be update automatically after your push branch

**Comment by MichalFoksa** [comment]
:) Yes, but I think then PR would look bit messy and the final intention of feature in PR could me missed (especially if there was more commits in the PR). I am still learning Github on the go.

**Pull request merged**
