### PR TITLE
Deprecate Request#setConnectionKeepAlive()

### PR DESCRIPTION
**Pull request by wldaunfr**
See https://github.com/fernandezpablo85/scribe-java/pull/520 for details.

### CODE REVIEW

**Comment by rockihack** [comment]
Please remove `System.setProperty("http.keepAlive", ...);` soon. It's a nasty thing to modify global jvm settings. `OAuth10aServiceImpl.getRequestToken()` also uses `OAuthRequest` and keepAlive defaults to false. There is currently no way to modify this behavior and it results in large ssl overhead if you send many requests.

https://github.com/scribejava/scribejava/blob/04195020558ea17ba1c271b85ef40977055942c8/scribejava-core/src/main/java/com/github/scribejava/core/oauth/OAuth10aServiceImpl.java#L45

**Comment by kullfar** [comment]
outdated. In case it's actual, rebase on the master pls

**Comment by rockihack** [comment]
The issue is not outdated.
As long as you use `System.setProperty("http.keepAlive", ...);` it remains the same.

**Comment by kullfar** [comment]
yep. you are right. reopening the issue

**Comment by kullfar** [comment]
eventualy have merged ;-) Thx to all

**Comment by kullfar** [comment]
fixed

**Pull request closed without merging**
