### PR TITLE
Add support for the Wunderlist API

### PR DESCRIPTION
**Pull request by M-F-K**
Note: had to add the request.addHeader("X-Client-ID", apiKey); cin the example to make it work, this seems like a dirty way of doing it, but I could not think of a better solution.

### CODE REVIEW

**Comment by kullfar** [comment]
Hi,

as for "request.addHeader("X-Client-ID", apiKey);"
It's better to implement custom Service, like this one:
https://github.com/scribejava/scribejava/blob/master/scribejava-apis/src/main/java/com/github/scribejava/apis/service/MicrosoftAzureActiveDirectoryService.java#L23

**Comment by kullfar** [comment]
I'm waiting for test user credential to run the example

**Comment by M-F-K** [comment]
I mailed them about s month ago to your “kullfar” Gmail account.  They are the ones I use dayli.  When you are testing please create a new list for testing purposes, ( the one allready there I am currently using)

Sorry for the late ansver .

Regards
Michael.

**Comment by kullfar** [comment]
Hi, you've sent just application credentials, I need user credentials as well.

> When you are testing please create a new list for testing purposes, ( the one allready there I am currently using)

Sorry, I didn't catch what list did you mean?

**Comment by M-F-K** [comment]
@kullfar sen't a mail some days ago with user credentials. Regarding the list I where usin, - i have deleted it, so go nuts, the account is yours =)

**Comment by kullfar** [comment]
Ok, I saw the email. I'll return to this Pull Request a bit later.
Thanks!

**Comment by kullfar** [comment]
Hi, I have merged your Pull Request with some changes.
The main - I moved ```request.addHeader("X-Client-ID", apiKey);``` to https://github.com/scribejava/scribejava/blob/master/scribejava-apis/src/main/java/com/github/scribejava/apis/service/WunderlistOAuthService.java

no need to add this header manually in Example or in production

**Pull request closed without merging**
