### PR TITLE
Add Wechat oauth2 support

### PR DESCRIPTION
**Pull request by zuoc**
Hello! 

I add Wechat(http://www.wechat.com/) support.

You can complete the test through the https://mp.weixin.qq.com/debug/cgi-bin/sandbox?t=sandbox/login.

Before that, you need to set up a server to receive WeChat‘s messages.

Here's the golang code I used to build the test server

```go
package main

import (
	"net/http"
	"log"
	"io"
)

func main() {
	http.HandleFunc("/message", func(w http.ResponseWriter, r *http.Request) {
		r.ParseForm()
		log.Println(r.Form)
		io.WriteString(w, r.Form.Get("echostr"))
	})

	http.HandleFunc("/callback", func(w http.ResponseWriter, r *http.Request) {
		r.ParseForm()
		log.Println(r.Form)
	})

	log.Fatal(http.ListenAndServe(":8088", nil))
}

```

### CODE REVIEW

**Comment by zuoc** [comment]
Hi.
What's the problem in this pull request?

**Comment by kullfar** [comment]
Hi, it's ok, just a lack of time. I'll get it soon

**Comment by zuoc** [comment]
ok，thanks

**Comment by kullfar** [comment]
Hi, for the moment, it's hard to run the example.
First of all I need test application credentials - client_id and client_secret.
And then possibility to login somehow, so I need test user credentials.

This link  https://mp.weixin.qq.com/debug/cgi-bin/sandbox?t=sandbox/login didn't help me. I can't register new apps and users. It's too time expensive for me, sorry.

There was the same problem with WeChat in this PR
https://github.com/scribejava/scribejava/pull/739

**Comment by zuoc** [comment]
You can visit http://www.wechat.com/ first, download the app and register an account.

Then visit  https://mp.weixin.qq.com/debug/cgi-bin/sandbox?t=sandbox/login  and login to the test platform using the above registered account

**Comment by kullfar** [comment]
Sorry, I can't register the account and/or app. It's time consuming task for me (c) https://github.com/scribejava/scribejava/wiki/FAQ#when-will-you-support-insert_api_here-

**Comment by Addvilz** [comment]
Any chance this PR could be resurrected? WeChat is way larger auth provider than many of the ones already implemented (1b+ users).

**Comment by kullfar** [comment]
why not? I'm still in lack of any credentials to test the changes.
As I remember last time registration on wechat just didn't work.
If someone can provide test app's and test user's credentials, it will be great chance to merge this or another Pull Request with WeChat functionality

**Comment by Addvilz** [comment]
Funny as it is, I just tried, seems like WeChat international account registration has been suspended...

Unless there is someone based in mainland China who can provide a test account, this is unlikely to succeed. Pity.

**Comment by kullfar** [comment]
And as I remember, it was impossible to login from outside of China even if you have login+password. There were a lot of additional questions.
I think, if WeChat is a cool company, they should provide "test user" functionality as Facebook does.

**Comment by kullfar** [comment]
Anyway, it's quite easy to use your own 1 class with API (in some cases a couple) and ScribeJava as dependency.

**Pull request closed without merging**
