### PR TITLE
issue #793 - Support for client-credentials grant.

### PR DESCRIPTION
**Pull request by vivin**
Adds support for retrieving an access token using client-credentials grant.

### CODE REVIEW

**Comment by vivin** [comment]
@kullfar is this ok?

**Comment by kullfar** [comment]
Sorry, for the delay, was on vacation, I will try to return to this issue i next couple of week

**Comment by vivin** [comment]
@kullfar oh, my apologies! Didn't realize you were on vacation -- hope you had fun! :)

**Comment by kullfar** [comment]
All is good.
But I have made some refactoring about Client Authorization
https://github.com/scribejava/scribejava/commit/82f38333b9fd53291f32f29638ee473c578f9900
2.3.  Client Authentication https://tools.ietf.org/html/rfc6749#section-2.3

Si, I have fixed your PR a bit and merged it to the master
https://github.com/scribejava/scribejava/commit/68919e6331490da8a2fc6be1485d4c53ff4db894

Thanks!

**Pull request merged**
