### PR TITLE
Add Garmin Connect API (https://developer.garmin.com/)

### PR DESCRIPTION
**Pull request by m-rm**
Unfortunately I can't provide test credentials since I'm using a company account. (account registration is not open, it has to be requested via https://www.garmin.com/en-US/forms/health-api-request/)

### CODE REVIEW

**Comment by kullfar** [comment]
Thanks for the Pull Request, but unfortunately I can't accept changes without testing them

**Comment by m-rm** [comment]
Ok, no problem

**Comment by lisadesouza89** [comment]
any update if this is going to be merged soon?

**Comment by kullfar** [comment]
@lisadesouza89 , the Pull Request is closed, there is no plans to merge it.
If you could provide test app credentials and test user credential to run the example, the chances of merging will increase.

**Pull request closed without merging**
