### PR TITLE
Add Kakao API

### PR DESCRIPTION
**Pull request by v0o0v**
Support for Kakao API
See https://developers.kakao.com/docs/latest/ko/kakaologin/rest-api for details

### CODE REVIEW

**Comment by v0o0v** [comment]
@kullfar plz check email. I've sent some info of credentials to test.

**Comment by v0o0v** [comment]
@kullfar check this PR. please.

**Comment by kullfar** [comment]
Hi @v0o0v!
Thx for the Pull Request and sorry for the delay, I was quite a busy.
I have run the example with provided credentials and got the error
```error="invalid_grant", error_description="Invalid redirect: https://b***r.net/c***k does not match one of the registered values. Please check app settings on kakao developer site."```

**Comment by kullfar** [comment]
I have used the callback url from the email you sent me

**Comment by v0o0v** [comment]
Hi @kullfar 

Because of the long period of time, the previously created test information was deleted. So I 've regenerate and sent. Please check your email.

**Comment by kullfar** [comment]
Cool! Thanks for the rapid answer. I have tested and have merged to the master without major modifications. Thanks for the clean Pull Request!

**Pull request merged**
