### PR TITLE
Add Naver API

### PR DESCRIPTION
**Pull request by chooco13**
Support for Naver API
See https://developers.naver.com/products/login/api for details

### CODE REVIEW

**Comment by kullfar** [comment]
looks nice.
send me app and user credential to run the Example, pls
https://github.com/scribejava/scribejava/wiki/FAQ#when-will-you-support-insert_api_here-

Thanks!

**Comment by kullfar** [comment]
Have merged to the master + 1 commit with readme and changelog entries

**Comment by kullfar** [comment]
Thx again

**Comment by chooco13** [comment]
It was my first open source contribute

Really thank you for your kindness!

**Comment by kullfar** [comment]
Welcome and congrats!

**Pull request merged**
