### PR TITLE
add support to get access token with additional params

### PR DESCRIPTION
**Pull request by jujusharp**
in some case, the server may need some additional params, so i can create request with some additional params to get the access token

### CODE REVIEW

**Comment by kullfar** [comment]
Travis said "All checks have failed"

**Comment by kullfar** [comment]
What are these cases?
If some standard flow, it will be better to add support for this param(s) in the core.
Some very nonstandard params, specific to the one concrete XXXAPI - it can have it's own XXXService.java with overrided createAccessTokenRequest method or hardcoded params in the access_token url String in XXXAPI.java (method getAccessTokenEndpoint)

I don't believe, that a lot of OAuth servers give opportunity to send additional params while getting access token ;-)

**Comment by jujusharp** [comment]
In my case, The server need to double check which client view(client view means if the client is from web, mobile or pc) for the token, and this param is not only with the redirect url in the first step.

**Comment by kullfar** [comment]
Can creating XXXService.java help you?
this type of classes intends for such custom logic.

**Comment by jujusharp** [comment]
OK, I think the best choice is to create a custom service to satisfied the requirement.
Thanks again!

**Comment by kullfar** [comment]
Welcome. You can provide this Custom Service and new API in a new PullRequest then ;-)

**Pull request closed without merging**
