### PR TITLE
Add support for Yammer using OAuth 2

### PR DESCRIPTION
**Pull request by janstey**
Fix for issue #393

### CODE REVIEW

**Comment by fernandezpablo85** [comment]
Hey @janstey, since Yammer dropped OAuth1.0 support seems like adding this would be useful for some users. Thanks for your contribution, it looks like your patch is going in.

**Comment by fernandezpablo85** [comment]
See https://github.com/fernandezpablo85/scribe-java/issues/460

**Comment by fernandezpablo85** [comment]
Yeah, that sucks, would you mind removing them from the pr? (just delete them and commit, the PR will update automatically)

**Comment by janstey** [comment]
Done.

**Comment by fernandezpablo85** [comment]
Just one more tweak, please remove the JsonTokenExtractor modifications. If you like, you can submit it as a different PR and we can discuss it over there.

**Comment by kullfar** [comment]
outdated. In case it's actual, rebase on the master pls

**Pull request closed without merging**
