### PR TITLE
Remove Kaixin api

### PR DESCRIPTION
**Pull request by zawn**
its official document has been unable to open.
http://wiki.open.kaixin001.com/index.php?id=OAuth2.0%E6%96%87%E6%A1%A3

http://www.kaixin001.com/platform/feedback.php

image

English translation：
Sorry, the Kaixin Open Platform has been discontinued. Please check the online documentation for technical issues.

### CODE REVIEW

**Comment by kullfar** [comment]
it does still works somehow
```
1.Kaixin20Example returns me {"error_code":"400","request":"/oauth2/authorize","error":"40004:Error: \u5e94\u7528\u4fe1\u606f\u9519\u8bef"}
telling, that I have "Application information error".
Doesn't look that thay have completely turn of their servers.
```
https://github.com/scribejava/scribejava/pull/859#issuecomment-412557516

**Comment by zawn** [comment]
@kullfar The appid that can't be obtained, the official document can't be opened. Don't worry, this product is really dead。

**Comment by kullfar** [comment]
Presence of this class doesn't hurt either ;-)

**Comment by kullfar** [comment]
I just see some live from kaixin api and do not want to check it thoroughly

**Comment by kullfar** [comment]
Does anybody still need this PR open?

**Pull request closed without merging**
